#!/usr/bin/env bash
# shellcheck shell=sh

MESSAGE="$1"
CHANNEL="#general"
USERNAME=""
ICON=":computer:"

if [ ! "$LOCAL_SLACK_WEBHOOK" ]; then
    echo "LOCAL_SLACK_WEBHOOK environment variable is not defined"
    exit 1
fi

options=$(getopt --long channel:,username:,icon: --options "" -- "$@")
eval set -- "$options"

while true; do
    case $1 in
        --icon)
            ICON="$2"
            shift 2
            ;;
        --username)
            USERNAME="$2"
            shift 2
            ;;
        --channel)
            CHANNEL="$2"
            shift 2
            ;;
        --)
            MESSAGE="${*:2}"
            shift
            break
            ;;
        *)
            echo "Internal error!"
            exit 1
            ;;
    esac
done

json_init() {
    TMP_FILE=$(mktemp)
    echo "{}">"$TMP_FILE"
}

json_set() {
    key="$1"
    value=${*:2}

    content=$(jq ".$key = \"$value\"" "$TMP_FILE") && echo "$content">"$TMP_FILE"
}

json_destroy() {
    rm "$TMP_FILE"
}


INVOKER=$(ps -ocmd= -p $PPID)
FROM="$(whoami)@$(hostname)"
MESSAGE="$MESSAGE\n\nEnviado desde $FROM:$0 ($INVOKER)"

json_init
json_set channel "$CHANNEL"
json_set username "${USERNAME:-$FROM}"
json_set text "$MESSAGE"
json_set icon_emoji "$ICON"

curl -X POST --silent --data-urlencode "payload=$(cat "$TMP_FILE")" "$LOCAL_SLACK_WEBHOOK"

json_destroy
