#!/usr/bin/env sh

domains_file=$CHECK_SITES_DOMAINS_FILE

[ ! -f "$domains_file" ] && domains_file=~/.config/check-sites/domains
[ ! -f "$domains_file" ] && color red "Domains file [$domains_file] do not exists! Create one there or specify the location with CHECK_SITES_DOMAINS_FILE env variable" && exit 1

check() {
    cat <"$domains_file" | while read -r domain; do
        check-cert "$domain"
    done
}

edit() {
    eval "$EDITOR" "$domains_file"
}

[ ! "$@" ] && check || "$@"
