#!/usr/bin/env sh

domain="$1"

if [ -z "$domain" ]; then
    command=$(basename "$0")
    echo "Usage: $command <domain>"

    exit 1
fi

echo "Checking ssl certificate for [$(color blue "$domain")]..."
response=$(echo | openssl s_client -servername "$domain" -connect "$domain":443 2>/dev/null | openssl x509 -noout -issuer -subject -dates 2>/dev/null)

if [ -n "$response" ]; then

    expira=$(echo "$response" | grep "notAfter=" | cut -d= -f2)
    r_ts=$(date +%s --date "today +1 week")
    y_ts=$(date +%s --date "today +1 month")
    g_ts=$(date +%s --date "today +2 month")

    expira_ts=$(date +%s --date "$expira")

    if [ "$expira_ts" -ge "$r_ts" ]; then color=red; fi
    if [ "$expira_ts" -ge "$y_ts" ]; then color=yellow; fi
    if [ "$expira_ts" -ge "$g_ts" ]; then color=green; fi

    printf "Expires on: %s\n" "$(date --iso-8601 --date "$expira" | color $color)"
else
    printf "No certificate found!\n" | color red && exit 1
fi
