#!/usr/bin/env sh

check_statements_from_file() {
    ERROR=0

    printf "Truths of [%s]\n" "$(basename "$1" | color blue)"

    while read -r line; do
        if [ -n "$line" ]; then
            statement=$(echo "$line" | cut -d= -f1)
            expec_value=$(echo "$line" | cut -d= -f2- | tr -d "\n\r")
            evald_value="$(eval "$statement" 2>/dev/null | tr -d "\n\r")"
            printf '%s' "$(color gray .)"

            # evald_value="https://test.fuckermate.com/"
            if [ "$expec_value" != "$evald_value" ]; then
                [ -n "$DEBUG" ] && printf "Error on line [%s]\nThe result of [eval %s] was [%s], expected [%s]\n" "$line" "$statement" "$evald_value" "$expec_value"
                ERROR=1
            fi
        fi
    done <"$1"

    printf "\n[%s] at [%s]\n" "$([ $ERROR = 1 ] && color red FAILED || color green SUCCEDED)" "$(date --rfc-3339=ns | cut -d. -f1)"
    return $ERROR
}

check_statements_from_dir() {
    for file in "$1"/*; do
        [ -f "$file" ] && check_statements_from_file "$file"
    done
}

[ -f "$1" ] && {
    check_statements_from_file "$1"
    exit
}

[ -d "$1" ] && {
    check_statements_from_dir "$1"
    exit
}

color red "A file or directory containing truth statements files must be given as a first argument" && exit 1
