#!/usr/bin/env bash

reset=$(tput sgr0)

declare -A COLORS
COLORS[r]=$(tput setaf 1)
COLORS[g]=$(tput setaf 2)
COLORS[y]=$(tput setaf 3)
COLORS[b]=$(tput setaf 4)

# ----------------------------- helper functions ----------------------------- #

_c() {
    color=${COLORS[$1]}
    echo -ne "$color$2$reset"
}

_cn() {
    # shellcheck disable=SC2005
    echo "$(_c "$1" "$2")"
}

domain="$1"

if [ -z "$domain" ]; then
    command=$(basename "$0")
    echo "Usage: $command <domain>"

    exit 255
fi

echo "Checking ssl certificate for [$(_c b "$domain")]..."
expira=$(echo | openssl s_client -servername "$domain" -connect "$domain":443 2>/dev/null | openssl x509 -noout -issuer -subject -dates | grep "notAfter=" | cut -d "=" -f 2)

r_ts=$(date +%s --date "today +1 week")
y_ts=$(date +%s --date "today +1 month")
g_ts=$(date +%s --date "today +2 month")

expira_ts=$(date +%s --date "$expira")

if [ "$expira_ts" -ge "$r_ts" ]; then color=r; fi
if [ "$expira_ts" -ge "$y_ts" ]; then color=y; fi
if [ "$expira_ts" -ge "$g_ts" ]; then color=g; fi

echo -n "Expires on: "
_cn $color "$(date --iso-8601 --date "$expira")"

exit 0
