#!/usr/bin/env sh

# Description: Selects command from history and copy it to clipboard.

HISTFILE=~/.zsh_history

(cat $HISTFILE | cut -d';' -f2- | tac |
    fzf --height=40% --no-sort --header='Selecciona el comando para copiar al clipboard' |
    xsel -b) && echo "Comando copiado!"
