#!/usr/bin/env sh

# Description: Ask for confirmation to the user and returns 0 if yes, 1 otherwise.

lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

message="$1"
default="$2"
default="${default:-n}"
default="$(lower "$default")"

yn=$([ "$default" = "n" ] && printf "[y/N]" || printf "[Y/n]")

printf "%s %s " "$(color yellow "$message")" "$yn"
# read -r response
read response </dev/tty # Read from the terminal

response="$(lower "$response")"
response="${response:-$default}"

[ "$response" = "y" ]
