#!/usr/bin/env bash

# Description: fgh - Fuzzy google-crome history

fgh() {

    local cols sep google_history open
    cols=$((COLUMNS / 3))
    sep='{::}'

    if [ "$(uname)" = "Darwin" ]; then
        google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
        open=open
    else
        google_history="$HOME/.config/google-chrome/Default/History"
        open=xdg-open
    fi
    cp -f "$google_history" /tmp/h
    sqlite3 -separator $sep /tmp/h "select title, url from urls order by last_visit_time desc" |
        awk -F $sep '{printf "%s\t%s\n", $1, $2}' |
        fzf --ansi --multi --reverse --border --preview "color blue {2..}" --preview-window "1,bottom,border-top" --delimiter "\t" --with-nth 1,2 | 
        sed 's#.*\(https*://\)#\1#' | xargs $open >/dev/null 2>/dev/null
}

fgh