#!/usr/bin/env bash

# Description: Git commits on FZF

gitlog() {
    git log \
        --color="always" \
        --format="%C(cyan)%h %C(blue)%ar%C(auto)%d %C(yellow)%s%+b %C(black)%ae" "$@"
}

_viewGitLogLine="echo {} | grep -o '[a-f0-9]\{7\}' | head -1 | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"

cfzf() {
    fzf -i -e +s \
        --reverse \
        --tiebreak=index \
        --no-multi \
        --ansi \
        --preview="$_viewGitLogLine" \
        --header "enter: view, C-c: copy hash" \
        --bind "enter:execute($_viewGitLogLine | bat --decorations=never)" \
        --bind "ctrl-c:execute(git rev-parse {1} | xclip -r -selection clipboard)"
}

gitlog $@ | cfzf
