#!/usr/bin/env sh

get_headers() {
    curl --silent -I "$1"
}

status() {
    get_headers "$1" | head -n1 | cut -d' ' -f2
}

location() {
    get_headers "$1" | grep -i location: | cut -d' ' -f2-
}

if [ -z "$2" ]; then
    get_headers "$1"
    exit
fi

eval "$1 $2"
