#!/usr/bin/env bash

# Description: Send to Raspberry LCD screen thru tcp socket. Either a string or command as first argument or message from stdin

RASP_SCREEN_IP=192.168.0.23
RASP_SCREEN_PORT=8000

send() {
    args=$@
    possible_command="$1"

    if [ -n "$args" ]; then
        type "$possible_command" 2>/dev/null >&2 && message=$(eval "$args") || message="$args"
    else
        message=$(cat)
    fi

    echo "$message" | socat - tcp:$RASP_SCREEN_IP:$RASP_SCREEN_PORT
}

listen() {
    { sudo bash -c "socat - tcp4-listen:$RASP_SCREEN_PORT,fork > /dev/tty1" & } && disown && printf "Listening on port %s\n" "$RASP_SCREEN_PORT"
}

[ "$1" = "listen" ] && listen || send $@
