#!/usr/bin/env sh

# Description: ripgrep thru fzf.

INITIAL_QUERY=""
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY' " \
    fzf --bind "change:reload:$RG_PREFIX {q} || true" \
    --ansi --query "$INITIAL_QUERY" \
    --height=50% --layout=reverse
