#! /usr/bin/env bash

# description: Launches rofi with exit options

echo "systemctl suspend|systemctl reboot|systemctl poweroff" \
    | rofi -dmenu -sep "|" -i -u 2 -a 1 -width -25 -window-title "Exit Options" -lines 3 \
    | head -n 1 \
    | xargs -i"XXX" --no-run-if-empty bash -c "XXX"
