#! /usr/bin/env bash

# description: Launches rofi with exit options

# echo "systemctl suspend|systemctl hibernate|systemctl hybrid-sleep|systemctl reboot|systemctl poweroff" \
#         | dmenu -sep "|" -i -width -25 -no-show-icons -p "" -lines 5 \
#         | head -n 1 \
#         | xargs -i"XXX" --no-run-if-empty bash -c "XXX"

echo "systemctl suspend|systemctl hibernate|systemctl hybrid-sleep|systemctl reboot|systemctl poweroff" \
    | rofi -dmenu -p "Exit" -sep "|" -steal-focus -normal-window \
    | head -n1 \
    | xargs -i"XXX" --no-run-if-empty bash -c "XXX"
