#! /usr/bin/env bash

# description: Launches rofi for selecting apps

rofi -sorting-method fzf \
    -steal-focus \
    -normal-window \
    -icon-theme Paper \
    -show drun run ssh combi keys \
    -modi combi,drun,run,ssh,keys
