#!/usr/bin/env sh

# Description: Restart network manager (systemctl).

distro_type=$(distro-like)

if [ "$distro_type" = "arch" ]; then
    sudo systemctl restart NetworkManager
    exit 0
fi

if [ "$distro_type" = "debian" ]; then
    sudo systemctl restart network-manager
    exit 0
fi

echo "Error: Unknown distro type: $distro_type"
