#! /usr/bin/env bash

# Description: rofi's like fzf

launch() {
  alacritty \
    --option "window.decorations=none" \
    --option "window.startup_mode=Windowed" \
    --option "window.opacity=.5" \
    --option "window.dimensions.columns=180" \
    --command $SHELL -c "rofiz select_app"
}

desktop_file() {
  find /usr/share/applications -name "*.desktop" 2>/dev/null &&
    find /usr/local/share/applications -name "*.desktop" 2>/dev/null &&
    find "$HOME/.local/share/applications" -name "*.desktop" 2>/dev/null &&
    find /var/lib/flatpak/exports/share/applications -name "*.desktop" 2>/dev/null &&
    find "$HOME/.local/share/flatpak/exports/share/applications" -name "*.desktop" 2>/dev/null
}

select_app() {
  selected="$(desktop_file | sed 's/.desktop//g' | sort | fzf -e -i -m --reverse --delimiter / --with-nth -1)"
  [ -z "$selected" ] && exit
  cd || return
  echo "$selected" | awk -F/ '{print $NF}' | while read -r line; do setsid gtk-launch "$line"; done
}

if [ ! $@ ]; then
  launch

  exit
fi

$@
