#!/usr/bin/env bash

# Description: Ask for confirmation to end the program by pressing some defined key (q by default).

key=${1:-Q}
message=${2:-"Press [%s] to exit"}

lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# shellcheck disable=SC2059
printf "$message\n" "$key"

while :; do
    read -r -n 1 k <&1
    if [ "$(lower "$k")" = "$(lower "$key")" ]; then
        break
    fi
done
